# Generated by Django 4.2.5 on 2023-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender_choices',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10),
        ),
    ]
