# Generated by Django 4.2.5 on 2023-09-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_gender_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_choices',
            new_name='color_choice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gender_choices',
            new_name='gender_choice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_choices',
            new_name='material_choice',
        ),
    ]
