# Generated by Django 4.2.5 on 2023-09-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_color_choices_product_color_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender_choice',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_choice',
            new_name='material',
        ),
    ]
