# Generated by Django 4.2.5 on 2023-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_gender_choice_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_choice',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('grey', 'Grey'), ('red', 'Red'), ('cream', 'Cream'), ('brown', 'Brown'), ('orange', 'Orange'), ('multicolor', 'Multicolor')], default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('leather', 'Leather'), ('leatherette', 'Leatherette'), ('suede', 'Suede'), ('fabric', 'Fabric'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
