# Generated by Django 4.2.5 on 2023-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_color_choice_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('grey', 'Grey'), ('red', 'Red'), ('cream', 'Cream'), ('brown', 'Brown'), ('orange', 'Orange'), ('multicolor', 'Multicolor')], max_length=20),
        ),
    ]
