# Generated by Django 4.2.5 on 2023-09-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariant_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='gender/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.material'),
        ),
    ]
