# Generated by Django 4.2.5 on 2023-09-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_gender_material_remove_productvariant_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVariation',
            new_name='ProductVariation',
        ),
    ]
