# Generated by Django 4.2.5 on 2023-09-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_sizevariation_productvariation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Гендер', 'verbose_name_plural': 'Гендеры'},
        ),
    ]
