# Generated by Django 4.2.5 on 2023-09-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_gender_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size')},
        ),
    ]
