# Generated by Django 4.2.5 on 2023-09-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productvariation_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Товар | Размер', 'verbose_name_plural': 'Товар | Размер'},
        ),
    ]
