# Generated by Django 4.2.5 on 2023-09-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productvariation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
