# Generated by Django 4.2.5 on 2023-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
