# Generated by Django 4.2.5 on 2023-10-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_review_first_name_review_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
