# Generated by Django 4.2.5 on 2024-01-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_review_options_product_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_visit',
        ),
    ]
