# Generated by Django 4.2.5 on 2024-01-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
