# Generated by Django 4.2.5 on 2023-09-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
    ]
