# Generated by Django 4.2.5 on 2023-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
        ),
    ]
