# Generated by Django 4.2.5 on 2023-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
        ),
    ]
