# Generated by Django 4.2.5 on 2023-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
