# Generated by Django 4.2.5 on 2023-10-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_user_alter_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
